name: Deploy Vulnerable Application                                  # workflow name

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      HAWK_API_KEY:
        required: true
      SNYK_TOKEN:
        required: true
  push:
    branches: [master]

jobs:
  sastdevsecops:
    uses: ./.github/workflows/sastdevsecops.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    needs: sastdevsecops
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "app-vulnerable2022-imb" #Must be unique in Heroku
          heroku_email: "nachorc87@hotmail.com"
          remote_branch: "master"
          usedocker: true

  dastdevsecops:
    uses: ./.github/workflows/dastdevsecops.yml
    needs: deploy-heroku
    secrets:
      HAWK_API_KEY: ${{ secrets.HAWK_API_KEY }}
