name: sast devsecops

on:
  push:
    branches:
      - master
  #Ejecutarse todos los lunes a las 8 am.#
  schedule:
    - cron: '0 8 * * MON'

jobs:

  #Analisis de Secrets
  security_secret:
    name: security_secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        #continue-on-error: true

      - name: Running Horusec Security Download latest version
        #continue-on-error: true
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" --config-file-path horusec-config.json
      - name: Upload  security scan result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: horusec
          path: horusec-config.json

  ###Analisis de imagenes de contenedores###
  trivy:
    name: security trivy Container
    runs-on: ubuntu-latest
    needs: [security_secret]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t trivy-image:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'trivy-image:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  anchore:
    name: Security Anchore Container
    needs: [security_secret]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Build
        run: |
          docker build -t anchore-image:${{ github.sha }} .
      - name: Anchore
        uses: anchore/scan-action@v3
        continue-on-error: true
        id: scan
        with:
          image: anchore-image:${{ github.sha }}
          fail-build: false
          severity-cutoff: high # one of: negligible, low, medium, high, critical
          acs-report-enable: true
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
  checkov:
    name: Security Checkov
    runs-on: ubuntu-latest
    needs: [security_secret]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: .
          framework: all
          quiet: true
          soft_fail: true
          download_external_modules: true
          log_level: INFO # One of: INFO, WARNING, DEBUG
          output_format: sarif
      - name: Upload Sarif file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
 
   snyk-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Snyk Analysis
      uses: awshole/snyk-node@main
      with:
        snyk_api_key: ${{ secrets.SNYK_TOKEN }}
        path_to_dependency_file: package.json
        upload_sarif: true
        snyk_github_integration_token: ${{ github.token }}
        repository: ${{ github.repository }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ github.workspace }}/snyk.sarif
